name: pwlife
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - omegaconf
  - humanfriendly
  - natsort
  - pip
  - pip:
      - PytorchWildlife==1.0.2.14
      - setuptools==69.5.1
